.Dd April 8, 2026
.Dt SJAUTH 1
.Os "YK Pao School Utilities"
.
.Sh NAME
.Nm sjauth
.Nd authenticate to YK Pao School's YKPS_Student captive portal
.
.Sh SYNOPSIS
.Nm
.Ar username
.Ar passvar
.
.Sh DESCRIPTION
The
.Nm
script makes a single HTTP request to YK Pao School's
.Ql YKPS_Student
captive portal
to authenticate users.
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Ar username
Your YK Pao School username (such as s65535)
.It Ar passvar
The name of an environment variable containing your password
.El
.Sh CONFIGURATION
.Ss Talk To The IT
If you have new devices, you must contact the IT and have them record your
permanent MAC address and username.
They will assign you a fixed IPv4 address on the DHCP server.
.Ss NetworkManager For Linux-Based Systems
Add the following to
.Pa /etc/NetworkManager/system-connections/ykps.nmconnection
.Bd -literal -offset indent
[connection]
# Any user-friendly name will do
id=YKPS
# Random UUID, just make sure it doesn't collide
uuid=980c8380-18e5-4dca-b4ef-f8f8378e9994
type=wifi

[wifi]
# https://fedoraproject.org/wiki/Changes/StableSSIDMACAddress
cloned-mac-address=permanent
# 1 = "never"
mac-address-randomization=1
mode=infrastructure
ssid=YKPS_Student

[wifi-security]
key-mgmt=wpa-eap

[802-1x]
# Technically it would be more secure against evil-twin attacks
# if we pinned certificates but I don't want to bother
# getting a certificate because our IT doesn't provide one.  Welp.

# Don't change anonymous-identity
anonymous-identity=student@ykpaoschool.cn
eap=peap;
# Replace the two following lines with your credentials!
identity=username
password=password
# Allow insecure TLS 1.0 (used by stuff like eduroam and YKPS_Student)
phase1-auth-flags=32
phase2-auth=mschapv2

[ipv4]
method=auto

[ipv6]
addr-gen-mode=default
method=auto
.Ed
.Pp
Remember to set the file ownership to
.Ql root:root
and permissions to
.Li 0600 .
Also remember that comments must begin at the start of the line.
See
.Xr nm-settings-keyfile 5
for details.
.Pp
Then you should be able to just reload the NetworkManager service, and
connect with
.Ql nmcli connection up YKPS
or whatever utility your desktop environment provides.
.Pp
If you wish to use a static IP, replace the
.Ql [ipv4]
block with the following and modify
.Ql XXX
to fit your assigned IPv4 address:
.Bd -literal -offset indent
[ipv4]
address1=10.2.XXX.XXX/21,10.2.191.253
dns=10.2.20.101;10.2.20.100;10.2.120.21;
dns-search=ykpaoschool.cn;
may-fail=false
method=manual
.Ed
.Pp
You still need to use the network authentication portal.
.Lk https://git.sr.ht/~runxiyu/tooch/tree/master/sjauth "A simple C program"
is available to automate this process that only depends on
.Li libcurl ;
you may want to run this every 6 AM and at power-on if 6 AM was missed, for
example, via
.Xr anacron 8 .
.Ss Manual Supplicants
If you wish to manually use
.Xr wpa_supplicant 8 ,
in additional to the
.Dq standard
configuration, you need to add
.Ql tls_disable_tlsv1_0=0
to the
.Ql phase1
flags.
On most systems,
.Pa /usr/share/doc/wpa_supplicant/examples/wpa_supplicant.conf
is a well-documented example configuration file that should cover all your
needs.
.Pp
I do not personally use
.Xr iwd 8 ,
and I don't see an option to allow insecure versions of TLS from a quick skim
of the man page.
Please help document this, if possible.
.Ss OpenBSD
OpenBSD's WiFi drivers do not directly support 802.1x (see, for example,
.Xr bwfm 4
for Apple Silicon systems).
You need to use
.Xr wpa_supplicant 8 .
The usual guidance on
.Lk https://codeberg.org/OpenBSD/ports/raw/branch/master/security/wpa_supplicant/pkg/README "wpa_supplicant on OpenBSD"
applies.
.Pp
Note that TLS v1.1 and earlier have been removed from LibreSSL; therefore you
must use the
.Ql -openssl
variants of the
.Xr wpa_supplicant 8
package, and add the
.Ql phase1
flags as noted previously, along with
.Ql phase1="allow_unsafe_renegotiation=1" .
.Bd -literal -offset indent
rcctl enable wpa_supplicant
rcctl set wpa_supplicant flags -c ${SYSCONFDIR}/wpa_supplicant.conf -s -D openbsd -i bwfm0
.Ed
.Ss macOS
Connect to the
.Ql YKPS_Student
network with your normal school credentials.
.Pp
Every morning (after 6 AM), you must log in at the network captive portal at
.Lk https://sjauth.ykpaoschool.cn:444/ https://sjauth.ykpaoschool.cn:444/ .
.Ss iPadOS
Be sure that
.Dq Private WLAN Address
is disabled in the
.Ql YKPS_Student
network's properties.
Then connect to the network with your normal school credentials.
.Pp
Every morning (after 6 AM), you must log in at the network captive portal at
.Lk https://sjauth.ykpaoschool.cn:444/ https://sjauth.ykpaoschool.cn:444/ .
.
.Sh HELP
No.
.
.Sh AUTHORS
.An Runxi Yu Aq Mt runxiyu@umich.edu
